# Generated by Django 2.1.4 on 2019-01-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='餐廳名稱')),
                ('address', models.CharField(max_length=100, verbose_name='餐廳地址')),
                ('food_types', models.CharField(max_length=50, verbose_name='餐廳類型')),
                ('visit_time', models.DateField()),
                ('purpose', models.CharField(max_length=10, verbose_name='造訪目的')),
                ('short_comment', models.CharField(max_length=255, verbose_name='短評')),
            ],
            options={
                'verbose_name': '餐廳',
            },
        ),
    ]
